# Generated by Django 6.1.1 on 2026-09-14 06:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(default='RAZORPAY', max_length=40)),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-processed_at',),
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='provider_order_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
