# Generated by Django 6.1.1 on 2026-09-14 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_payment_status_returnrequest_refund_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PAYMENT_PENDING', 'Payment pending'), ('PAID', 'Paid'), ('PROCESSING', 'Processing'), ('CANCELLATION_PENDING', 'Cancellation pending'), ('SHIPPED', 'Shipped'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PAYMENT_PENDING', max_length=24),
        ),
        migrations.AlterField(
            model_name='refund',
            name='return_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refund', to='orders.returnrequest'),
        ),
    ]
