# Generated by Django 6.1.1 on 2026-09-13 08:47

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Enter the phone number in E.164 format, for example +919876543210.', regex='^\\+[1-9]\\d{7,14}$')])),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='customer_avatars/')),
                ('shopping_preference', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex'), ('none', 'No preference')], default='none', help_text='Used only to personalize the storefront.', max_length=10)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'CUSTOMER PROFILES',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(choices=[('home', 'Home'), ('work', 'Work'), ('other', 'Other')], default='home', max_length=20)),
                ('recipient_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Enter the phone number in E.164 format, for example +919876543210.', regex='^\\+[1-9]\\d{7,14}$')])),
                ('address_line_1', models.CharField(max_length=255)),
                ('address_line_2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country_code', models.CharField(help_text='Two-letter ISO country code, such as IN or US.', max_length=2, validators=[django.core.validators.RegexValidator(message='Enter a two-letter uppercase ISO country code, for example IN or US.', regex='^[A-Z]{2}$')])),
                ('is_default_shipping', models.BooleanField(default=False)),
                ('is_default_billing', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'ADDRESSES',
                'ordering': ('-is_default_shipping', '-created_at'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default_shipping', True)), fields=('user',), name='one_default_shipping_address_per_user'), models.UniqueConstraint(condition=models.Q(('is_default_billing', True)), fields=('user',), name='one_default_billing_address_per_user')],
            },
        ),
    ]
